<script src="{{asset('../assets_frontend/js/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery-ui.js')}}"></script>
<script src="{{asset('../assets_frontend/js/popper.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/bootstrap.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery.stellar.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery.countdown.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('../assets_frontend/js/aos.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery.fancybox.min.js')}}"></script>
{{-- <script src="{{asset('../assets_frontend/js/jquery.sticky.js')}}"></script> --}}
<script src="{{asset('../assets_frontend/js/customSticky.js')}}"></script>
<script src="{{asset('../assets_frontend/js/jquery.mb.YTPlayer.min.js')}}"></script>
<script src="{{asset('../assets_frontend/js/main.js')}}"></script>
